/* tslint:disable */
/* eslint-disable */
/**
 * Hostinger Mail API
 *
 * API Version: 1.0.2
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */


export * from "./api";
export * from "./configuration";

